site_name: noted_documents
site_description: Documents service
repo_url: https://github.com/jsgilberto/noted-documents-service
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/jsgilberto">jsgilberto</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
